### ISSUE TITLE
Adding a new picture is not possible in PHP 7.3

### ISSUE THREAD

**Issue by Floffyko** [ConX/dokuwiki-plugin-custombuttons#20]
It seems that the Add Button - Icon - drop down Button is not working in the new environment. The same plug-in is perfect functional in php 5.4, but not in 7.3. Is there maybe an incompatibility with the latest DW?

**Comment by ConX** [comment]
It works for me at the latest version of Dokuwiki and with PHP v. 7.0.3. Could you please check the latest version and let me know what errors you get?
