### ISSUE TITLE
After plugin update still old plugin date shown

### ISSUE THREAD

**Issue by tmo26** [ConX/dokuwiki-plugin-custombuttons#21]
**Issue:** After updating the custombuttons plugin, "Installed version" is still showing the old date, resulting in the plugin still being shown as "updatable" despite the update already happened.

**After plugin update:**
Installed version:    2019-07-11
Your last update:    Fri, 18 Oct 2019 09:15:55 +0000
Available version:    2019-07-19

**Comment by ConX** [comment]
I am not sure what is causing this. Where do you see the last update being on October 18th?

**Comment by tmo26** [comment]
I see this in the extension manager:
![grafik](https://user-images.githubusercontent.com/12309103/76250562-dee47100-6245-11ea-9584-398b41602208.png)
But as you can see in the screenshot, the "Available version: 2019-07-19" is gone, and with it the issue described above.

Issue closed.
